#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t pearl"

echo "==================================="
echo "            Project Pearl          "
echo "==================================="
$L "Welcome to Android `getprop ro.build.version.release` / Pearl-`getprop ro.pearl.version`";
