# Versioning System
PEARL_BASE_VERSION = Sparky-White

ifeq ($(PEARL_BUILD_TYPE), OFFICIAL)
PEARL_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(DATE)-$(PEARL_BUILD_TYPE)
else

    # If PEARL_BUILD_TYPE is not defined, set to UNOFFICIAL
PEARL_BUILD_TYPE := UNOFFICIAL
PEARL_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(DATE)-$(PEARL_BUILD_TYPE)
endif

TARGET_PRODUCT_SHORT := $(subst pearl_,,$(PEARL_BUILD_TYPE))

# Set all versions
DATE := $(shell date -u +%Y%m%d)
PEARL_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
PEARL_BUILD_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(DATE)-$(PEARL_BUILD_TYPE)
PEARL_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(DATE)-$(PEARL_BUILD_TYPE)
PEARL_MOD_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(PEARL_BUILD_DATE)-$(PEARL_BUILD_TYPE)
PEARL_DISPLAY_VERSION := Pearl-$(PEARL_BASE_VERSION)-$(PEARL_BUILD_TYPE)
ROM_FINGERPRINT := Pearl/$(PEARL_BASE_VERSION)/$(TARGET_PRODUCT_SHORT)/$(PEARL_BUILD_DATE)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.pearl.build.version=$(PEARL_BUILD_VERSION) \
    ro.pearl.version=$(PEARL_VERSION) \
    ro.pearl.releasetype=$(PEARL_BUILD_TYPE) \
    ro.mod.version=$(PEARL_MOD_VERSION) \
    ro.pearl.display.version=$(PEARL_DISPLAY_VERSION) \
    ro.pearl.fingerprint=$(ROM_FINGERPRINT)
